name: keynote
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pypy2.7
  - r-base=3.4.1
  - geopandas
  - ipykernel
  - jupyter
  - jupyter_contrib_nbextensions
  - oct2py
  - octave
  - octave_kernel
  - palettable
  - pandas
  - pandoc
  - r-ggplot2
  - r-obistools
  - r-robis
  - rpy2
  - scikit-learn
  - pip:
    - git+https://github.com/python-visualization/folium.git
    - ads
